# NumPy 랩업 문제
다음 문제들은 NumPy의 기본 개념부터 고급 개념까지 순차적으로 학습할 수 있도록 설계되었습니다. 

문제의 난이도는 하, 중, 상으로 나뉘어 있으며, 각각 5개의 문제로 구성되어 있습니다.



## 1단계 문제


1. 크기가 10인 null 벡터를 만드세요. (힌트: `np.zeros()`)


In [1]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. numpy 버전과 설정을 출력하세요. (힌트: `np.__version__`, `np.show_config()`)


In [3]:
print(np.__version__), print(np.show_config())

2.3.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

(None, None)

3. 값이 10에서 49까지인 벡터를 만드세요. (힌트: `np.arange(10, 50)`)


In [5]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. 벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 `[::-1]`)


In [8]:
arr1 = arr[::-1]
arr1

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. 크기가 3x3이고 0에서 8까지의 값을 갖는 행렬을 만드세요. (힌트: `np.arange()`와 `reshape()`)


In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 2단계 문제


1. 1D 배열을 3x3 행렬로 변환하세요. (힌트: `reshape()`)


In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. 0에서 1 사이의 랜덤한 값으로 채워진 3x3 배열을 만드세요. (힌트: `np.random.random()`)


In [11]:
np.random.rand(3,3)

array([[0.17951149, 0.05164264, 0.24177756],
       [0.62483894, 0.739294  , 0.45031162],
       [0.84760964, 0.08013647, 0.27563882]])

3. 5x5 단위 행렬을 만드세요. (힌트: `np.eye(5)`)


In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. 임의의 1D 배열에서 가장 큰 값의 인덱스를 찾으세요. (힌트: `np.argmax()`)


In [15]:
arr2 = np.random.rand(3,3)
print(arr2)
arr2.argmax()

[[0.35857272 0.78032554 0.92161238]
 [0.09122328 0.21890434 0.25489195]
 [0.84580392 0.80596892 0.36577354]]


np.int64(2)

5. 크기가 10인 배열을 생성하고, 3에서 8까지의 값을 0으로 바꾸세요. (힌트: 슬라이싱과 배열 인덱싱)


In [17]:
arr3 = np.arange(10)
arr3[3:9] = 0
arr3

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 9])

## 3단계 문제


1. 임의의 배열에서 가장 작은 값과 가장 큰 값을 교환하세요. (힌트: `np.min()`, `np.max()`와 인덱싱)


In [22]:
arr4 = np.random.rand(10)
print(arr4)
print("**********************************************")
arr4_min = np.argmin(arr4)
arr4_max = np.argmax(arr4)
arr4[arr4_min], arr4[arr4_max] = arr4[arr4_max], arr4[arr4_min]
print(arr4)

[0.23291457 0.00805146 0.46943554 0.61521659 0.81385455 0.04859767
 0.71197754 0.49876041 0.5111167  0.01895121]
**********************************************
[0.23291457 0.81385455 0.46943554 0.61521659 0.00805146 0.04859767
 0.71197754 0.49876041 0.5111167  0.01895121]


2. 3차원 배열의 각 슬라이스마다 평균값을 계산하세요. (힌트: `np.mean()`과 축 설정)


In [29]:
arr5 = np.arange(9).reshape(3,3)
print(arr5)
print("=========================")
arr5_1 = np.stack([arr5, arr5, arr5, arr5])
print(arr5_1)
arr5_1.shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]
  [6 7 8]]]


(4, 3, 3)

3. 크기가 100인 배열을 생성하고 평균, 표준편차를 계산하세요. (힌트: `np.mean()`, `np.std()`)


In [30]:
arr6 = np.arange(100)
print(np.mean(arr6)), print(np.std(arr6))

49.5
28.86607004772212


(None, None)

4. 주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: `np.unique()`와 `axis` 설정)


In [32]:
arr7 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [4,5,6]])
arr7_1 = np.unique(arr7, axis=0)
print(arr7_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5. 임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: `np.argsort()`와 슬라이싱)


In [34]:
arr8 = np.arange(100).reshape(10,10)
arr8_1 = arr8.flatten()   #1차원으로 펼치기
arr8_2 = np.argsort(arr8_1)   #배열 인덱스 순서 정렬
arr8_3 = arr8_2[-5:]   #가장 큰 값(뒤에서부터) 5개
arr8_4 = arr8_1[arr8_3]
print(arr8)
print(arr8_4)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[95 96 97 98 99]
