<a href="https://colab.research.google.com/github/jiyoung1634/hipython_rep/blob/main/30_AI_ML_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 규칙 기반 프로그램 - 전통적인 방식의 AI

규칙을 지정해야 한다.

In [ ]:
def my_function(x):
  return 5 * x + 7   # 규칙

val = int(input('숫자를 입력하세요 : '))
ret = my_function(val)
print(ret)

숫자를 입력하세요 : 9
52


# 머신러닝

규칙이 아닌 모델을 선정   
모델 : 데이터를 넣어준다 -> 학습 fit()   
모델 : 값을 넣어 결과를 확인한다 -> 예측 predict()

In [ ]:
import numpy as np
from sklearn import linear_model

In [ ]:
X_train = np.array([1,2,3,4,5,6,7]).reshape(-1, 1)   # 입력데이터
X_train

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [ ]:
Y_train = np.array([12,17,22,27,32,37,42])   # 결과데이터
model = linear_model.LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [ ]:
model.predict([[9]])   # 예측

array([52.])

# 딥러닝

모델이 정해져 있다.   
계층설정 : 입력층, 은닉층, 출력층   
모델 생성(계층)   
모델 설정 : compile   
모델 학습 (데이터) : fit   
학습한 모델로 예측 : predict

In [ ]:
import tensorflow as tf

In [ ]:
X_train = np.array([1,2,3,4,5,6,7]).reshape(-1, 1)
Y_train = np.array([12,17,22,27,32,37,42])

In [ ]:
# 모델 생성 - 계층
inputs = tf.keras.layers.Input(shape=(1,))
outputs = tf.keras.layers.Dense(units=1)(inputs)

In [ ]:
model = tf.keras.models.Model(inputs, outputs)

In [ ]:
# 모델 설정
model.compile(
    loss = tf.keras.losses.MeanSquaredError(),
    optimizer = tf.keras.optimizers.SGD()
    )

In [ ]:
# 데이터 넣고 학습시키기
model.fit(X_train, Y_train, epochs = 1000, verbose = 0)

In [ ]:
# 예측
model.predict(np.array([[9]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[52.014755]], dtype=float32)